### ISSUE TITLE
Package CoreFoundation-sys is not found in index

### ISSUE THREAD

**Issue by lelongg** [oxalica/nocargo#9]
I'm trying to use nocargo to compile a crate from a workspace using [serialport](https://docs.rs/serialport/latest/serialport/) on linux.

This crate add the following entry to *Cargo.lock*.

```
[[package]]
name = "CoreFoundation-sys"
version = "0.1.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "d0e9889e6db118d49d88d84728d0e964d973a5680befb5f85f55141beea5c20b"
dependencies = [
 "libc",
 "mach 0.1.2",
]
```

This does not prevent classic builds from succeeding but *nocargo* fails with `error: Package CoreFoundation-sys is not found in index`.

Minimal reproduction example: https://github.com/lelongg/nocargo-issue-9

**Comment by oxalica** [comment]
Fixed in c2ec828a219fba1a8d65040aadff74318513e40b
